/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mycompany;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Saif
 */
public class Ppalete extends javax.swing.JFrame {

    /**
     * Creates new form Ppalete
     */
    public Ppalete(String s) {
setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
       setExtendedState(JFrame.MAXIMIZED_HORIZ);
       setExtendedState(JFrame.DISPOSE_ON_CLOSE);
        this.setUndecorated(true);
        //this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.setVisible(true);        
//this.setUndecorated(false);
        initComponents();
        getContentPane().setBackground(new Color(204, 204, 255));
        wlname.setText(s);this.setTitle("BlueSZ");
        this.setAlwaysOnTop(true);

        /*setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setExtendedState(JFrame.DISPOSE_ON_CLOSE);
        //Ppalete.setUndecorated(true);
        setResizable(false);
        */
        Dsize.setVisible(false);
    Ss.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        gtotal = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        wlname = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        Dsize = new javax.swing.JPanel();
        Stens = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        WSize = new javax.swing.JTextField();
        LSize = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        dLSize = new javax.swing.JCheckBox();
        dWSize = new javax.swing.JCheckBox();
        Scalc = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        SpecialTotal = new javax.swing.JLabel();
        NPanel = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        HSize = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        Ds = new javax.swing.JRadioButton();
        Ss = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        nump = new javax.swing.JTextField();
        ptotal = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lnum = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        laard = new javax.swing.JTextField();
        lertfaa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lttol = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ltotal = new javax.swing.JLabel();
        ltens = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        ctt = new javax.swing.JCheckBox();
        baa = new javax.swing.JCheckBox();
        cdd = new javax.swing.JCheckBox();
        lsTotal = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dnum = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dertfaa = new javax.swing.JTextField();
        daard = new javax.swing.JTextField();
        dttol = new javax.swing.JTextField();
        dtotal = new javax.swing.JLabel();
        dtens = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cdt = new javax.swing.JCheckBox();
        bda = new javax.swing.JCheckBox();
        ddd = new javax.swing.JCheckBox();
        dsTotal = new javax.swing.JLabel();
        nnew = new javax.swing.JButton();
        neworder = new javax.swing.JButton();
        totalp = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        mtotal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("United Brothers (Palete)");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mycompany/12-128.png"))); // NOI18N
        jButton3.setText("<< Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel17.setText("Eng SaifZoghby");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
        );

        gtotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gtotal.setText("0.00 Cm");

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setText("Total Calculate (cm)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        wlname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        wlname.setText("jLabel18");

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Get Price");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButton1KeyTyped(evt);
            }
        });

        jLabel18.setText("How Many Palete You Want");

        Dsize.setBackground(new java.awt.Color(204, 204, 255));

        Stens.setText("10000");
        Stens.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                StensKeyTyped(evt);
            }
        });

        jLabel20.setText("/");

        WSize.setText("0");
        WSize.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                WSizeKeyTyped(evt);
            }
        });

        LSize.setText("0");
        LSize.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LSizeKeyTyped(evt);
            }
        });

        jLabel23.setText("Width");

        jLabel24.setText("Length");

        dLSize.setText("D");
        dLSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dLSizeActionPerformed(evt);
            }
        });

        dWSize.setText("D");
        dWSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dWSizeActionPerformed(evt);
            }
        });

        Scalc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Scalc.setText("0.00 Cm");

        jLabel26.setText("How Many Panels DS You Want ");

        SpecialTotal.setForeground(new java.awt.Color(0, 0, 153));
        SpecialTotal.setText("EGP");

        NPanel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100", "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "111", "112", "113", "114", "115", "116", "117", "118", "119", "120", "121", "122", "123", "124", "125", "126", "127", "128", "129", "130", "131", "132", "133", "134", "135", "136", "137", "138", "139", "140", "141", "142", "143", "144", "145", "146", "147", "148", "149", "150", "151", "152", "153", "154", "155", "156", "157", "158", "159", "160", "161", "162", "163", "164", "165", "166", "167", "168", "169", "170", "171", "172", "173", "174", "175", "176", "177", "178", "179", "180", "181", "182", "183", "184", "185", "186", "187", "188", "189", "190", "191", "192", "193", "194", "195", "196", "197", "198", "199", "200" }));

        jLabel25.setText("Height");

        HSize.setText("0");

        jCheckBox1.setText("D");

        javax.swing.GroupLayout DsizeLayout = new javax.swing.GroupLayout(Dsize);
        Dsize.setLayout(DsizeLayout);
        DsizeLayout.setHorizontalGroup(
            DsizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DsizeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(DsizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dLSize)
                    .addGroup(DsizeLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(22, 22, 22))
                    .addComponent(LSize, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(DsizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DsizeLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(28, 28, 28))
                    .addComponent(dWSize, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(WSize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(DsizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addGroup(DsizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jCheckBox1)
                        .addComponent(HSize, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(Scalc, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DsizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DsizeLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Stens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SpecialTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        DsizeLayout.setVerticalGroup(
            DsizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DsizeLayout.createSequentialGroup()
                .addGroup(DsizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DsizeLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(DsizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox1)
                            .addComponent(Scalc)))
                    .addGroup(DsizeLayout.createSequentialGroup()
                        .addGroup(DsizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DsizeLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(DsizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel26)
                                    .addComponent(NPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(DsizeLayout.createSequentialGroup()
                                .addGroup(DsizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Stens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20))
                                .addGap(24, 24, 24)
                                .addComponent(SpecialTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DsizeLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(WSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dWSize))
                            .addGroup(DsizeLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dLSize)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        Ds.setBackground(new java.awt.Color(204, 204, 255));
        Ds.setText("Diffrent Size");
        Ds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DsActionPerformed(evt);
            }
        });

        Ss.setBackground(new java.awt.Color(204, 204, 255));
        Ss.setText("Same Size");
        Ss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SsActionPerformed(evt);
            }
        });

        jLabel19.setText("All Plank Of Palete ");

        nump.setText("1");
        nump.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numpKeyTyped(evt);
            }
        });

        ptotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ptotal.setForeground(new java.awt.Color(51, 51, 255));
        ptotal.setText("0.00 EGP");

        jLabel15.setBackground(new java.awt.Color(102, 255, 102));
        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setText("The Price Of  One Palete");

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Plank");

        lnum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100", "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "111", "112", "113", "114", "115", "116", "117", "118", "119", "120", "121", "122", "123", "124", "125", "126", "127", "128", "129", "130", "131", "132", "133", "134", "135", "136", "137", "138", "139", "140", "141", "142", "143", "144", "145", "146", "147", "148", "149", "150", "151", "152", "153", "154", "155", "156", "157", "158", "159", "160", "161", "162", "163", "164", "165", "166", "167", "168", "169", "170", "171", "172", "173", "174", "175", "176", "177", "178", "179", "180", "181", "182", "183", "184", "185", "186", "187", "188", "189", "190", "191", "192", "193", "194", "195", "196", "197", "198", "199", "200" }));

        jLabel1.setText("Length");

        laard.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                laardKeyTyped(evt);
            }
        });

        lertfaa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lertfaaKeyTyped(evt);
            }
        });

        jLabel4.setText("Number Of Panels");

        lttol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lttolActionPerformed(evt);
            }
        });
        lttol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lttolKeyTyped(evt);
            }
        });

        jLabel5.setText("Width");

        jLabel6.setText("Height");

        ltotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ltotal.setText("0.00 Cm");

        ltens.setText("10000");
        ltens.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ltensKeyTyped(evt);
            }
        });

        jLabel14.setText("/");

        ctt.setText("D");
        ctt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cttActionPerformed(evt);
            }
        });

        baa.setText("D");
        baa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baaActionPerformed(evt);
            }
        });

        cdd.setText("D");
        cdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cddActionPerformed(evt);
            }
        });

        lsTotal.setForeground(new java.awt.Color(0, 0, 153));
        lsTotal.setText("EGP");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(baa)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(27, 27, 27))
                                    .addComponent(ctt)
                                    .addComponent(lttol, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(laard, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                    .addComponent(cdd, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(lertfaa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ltotal, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ltens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lsTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ltens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lttol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(laard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cdd, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ctt, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(baa, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ltotal)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lsTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lertfaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("CubeWood (dokm)");

        jLabel8.setText("Number Of Cubes");

        dnum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100", "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "111", "112", "113", "114", "115", "116", "117", "118", "119", "120", "121", "122", "123", "124", "125", "126", "127", "128", "129", "130", "131", "132", "133", "134", "135", "136", "137", "138", "139", "140", "141", "142", "143", "144", "145", "146", "147", "148", "149", "150", "151", "152", "153", "154", "155", "156", "157", "158", "159", "160", "161", "162", "163", "164", "165", "166", "167", "168", "169", "170", "171", "172", "173", "174", "175", "176", "177", "178", "179", "180", "181", "182", "183", "184", "185", "186", "187", "188", "189", "190", "191", "192", "193", "194", "195", "196", "197", "198", "199", "200" }));

        jLabel9.setText("Length");

        jLabel10.setText("Width");

        jLabel11.setText("Height");

        dertfaa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dertfaaKeyTyped(evt);
            }
        });

        daard.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                daardKeyTyped(evt);
            }
        });

        dttol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dttolKeyTyped(evt);
            }
        });

        dtotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dtotal.setText("0.00 Cm");

        dtens.setText("10000");
        dtens.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dtensKeyTyped(evt);
            }
        });

        jLabel16.setText("/");

        cdt.setText("D");
        cdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdtActionPerformed(evt);
            }
        });

        bda.setText("D");
        bda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdaActionPerformed(evt);
            }
        });

        ddd.setText("D");
        ddd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dddActionPerformed(evt);
            }
        });

        dsTotal.setForeground(new java.awt.Color(0, 0, 153));
        dsTotal.setText("EGP");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(26, 26, 26)
                .addComponent(dnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cdt)
                                .addComponent(dttol, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(daard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bda, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel10))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dertfaa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ddd, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addComponent(dtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dsTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(dtens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addComponent(dsTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(daard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dertfaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dttol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ddd, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bda, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cdt, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(dtotal, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(dnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nump)
                    .addComponent(Ss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(Ds)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(26, 26, 26)
                        .addComponent(ptotal)
                        .addGap(124, 124, 124))))
            .addComponent(Dsize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ptotal)
                        .addComponent(jLabel15))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(nump, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(Ss)
                    .addComponent(Ds))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(Dsize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        nnew.setBackground(new java.awt.Color(153, 153, 255));
        nnew.setText("New");
        nnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nnewActionPerformed(evt);
            }
        });

        neworder.setBackground(new java.awt.Color(0, 204, 204));
        neworder.setText("AddOrder");
        neworder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                neworderActionPerformed(evt);
            }
        });

        totalp.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        totalp.setForeground(new java.awt.Color(51, 51, 255));

        jLabel12.setText("Metter Price");

        mtotal.setText("40");
        mtotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mtotalKeyTyped(evt);
            }
        });

        jLabel13.setText("EGP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wlname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(neworder)
                .addGap(18, 18, 18)
                .addComponent(nnew)
                .addGap(58, 58, 58))
            .addComponent(totalp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(52, 52, 52)
                .addComponent(gtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(jLabel12))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(wlname)
                        .addComponent(nnew)
                        .addComponent(neworder)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gtotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalp, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lttolKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lttolKeyTyped

        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            //    System.out.print(evt.getKeyLocation());
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_lttolKeyTyped

    private void laardKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_laardKeyTyped

        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
        /*if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE|| c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }*/    }//GEN-LAST:event_laardKeyTyped

    private void lertfaaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lertfaaKeyTyped

        char c = evt.getKeyChar();

        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_lertfaaKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (dttol.getText().equals("")
                || daard.getText().equals("")
                || dertfaa.getText().equals("")
                || lttol.getText().equals("")
                || laard.getText().equals("")
                || lertfaa.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter the values!!!");System.out.print(ltotal.getText());
        } else {
                CubeWood cw = new CubeWood();
                Plank ss = new Plank();
            String ttoll = dnum.getItemAt(dnum.getSelectedIndex());
                String lttoll = lnum.getItemAt(lnum.getSelectedIndex());
                double ds = cw.CubeWood(Integer.parseInt(ttoll), Integer.parseInt(dtens.getText()), Double.parseDouble(dttol.getText()), Double.parseDouble(daard.getText()), Double.parseDouble(dertfaa.getText()));
                    double ls = ss.Plank(Integer.parseInt(lttoll), Integer.parseInt(ltens.getText()), Double.parseDouble(lttol.getText()), Double.parseDouble(laard.getText()), Double.parseDouble(lertfaa.getText()));
            
            double sum = (ds + ls);
            ltotal.setText(ls+" Cm");dtotal.setText(ds+" Cm");
            gtotal.setText(sum + " Cm");
            
        }
//  JOptionPane.showMessageDialog(null, "Enter the values!!!");
        //else {
        //     Plank s = new Plank();
        //CubeWood cw=new CubeWood();
        //   String ttoll = lnum.getItemAt(lnum.getSelectedIndex());  String dttoll = dnum.getItemAt(dnum.getSelectedIndex());
        //double s = s.Plank(Integer.parseInt(ttoll), Double.parseDouble(lttol.getText()), Double.parseDouble(laard.getText()), Double.parseDouble(lertfaa.getText()));
        //double ds =  cw.CubeWood(Integer.parseInt(dttoll), Double.parseDouble(dttol.getText()), Double.parseDouble(daard.getText()), Double.parseDouble(dertfaa.getText())); 
        //System.out.print(ttoll);
//double dssum=(ss+ds);
        //      gtotal.setText(dssum+"  Cm"); 

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       /*Something Error 
        if (dttol.getText().equals("") || daard.getText().equals("") || dertfaa.getText().equals("") || lttol.getText().equals("") || laard.getText().equals("") || lertfaa.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Enter the values!!!");
        } else {
            try {
SpecialPlank SP=new SpecialPlank();
                CubeWood cw = new CubeWood();
                Plank s = new Plank();
                //float num = Float.parseFloat(dtens.getText());
String LPanel = NPanel.getItemAt(NPanel.getSelectedIndex());
                String ttoll = dnum.getItemAt(dnum.getSelectedIndex());
                String lttoll = lnum.getItemAt(lnum.getSelectedIndex());
                String ptotals=nump.getText();
                int ptotald=Integer.parseInt(ptotals);
double ST=SP.SpecialPlank(
        Integer.parseInt(LPanel),
        Integer.parseInt(Stens.getText()),
        Double.parseDouble(HSize.getText()),
        Double.parseDouble(WSize.getText()),
        Double.parseDouble(LSize.getText()));

                double ds = cw.CubeWood(Integer.parseInt(ttoll),
                        Integer.parseInt(dtens.getText()),
                        Double.parseDouble(dttol.getText()),
                        Double.parseDouble(daard.getText()),
                        Double.parseDouble(dertfaa.getText()));
                double ls = s.Plank(Integer.parseInt(lttoll),
                        Integer.parseInt(ltens.getText()),
                        Double.parseDouble(lttol.getText()),
                        Double.parseDouble(laard.getText()), 
                        Double.parseDouble(lertfaa.getText()));
                double dssum = (ls + ds+ ST);
                dtotal.setText(ds + " Cm");
                ltotal.setText(ls + " Cm");
                Scalc.setText(ST+" Cm");
//SpecialTotal.setText(cashDS+" EGP");
                gtotal.setText(dssum + " Cm");
                double cashprice = Integer.parseInt(mtotal.getText());
                double cashp = (cashprice * dssum);
                double totalCash=(cashp*ptotald);
                ptotal.setText(cashp + "  EGP");
totalp.setText("Total cash of "+ptotals+" paletes = "+totalCash+" EGP");
                //totalp.setText("Total cash of "+ptotals+" paletes = "+totalCash+" EGP");
                




//int paletesnum=Integer.parseInt(mtotal.getText());
//double cashDS=(ST*cash);

//double TCash=((cashp+cashDS));
//ptotal.setText(TCash + "  EGP");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "               Error \n\n"
                        + "Check value is not entered..!!!!");
            }
        }*/
       //this condition to check values
        if (dttol.getText().equals("") || daard.getText().equals("") ||
                    dertfaa.getText().equals("") || lttol.getText().equals("") || 
                    laard.getText().equals("") || lertfaa.getText().equals("")) {

                JOptionPane.showMessageDialog(null, "Enter the values!!!");
            } else {
            //this else to continue the calculat
                try {
                    //this two lines to call two methods
                    CubeWood cw = new CubeWood();
                    Plank s = new Plank();
                    //that three lines to save the context in string variables
                    String ptotals=nump.getText();
                             //float num = Float.parseFloat(dtens.getText());
                    String ttoll = dnum.getItemAt(dnum.getSelectedIndex());
                    String lttoll = lnum.getItemAt(lnum.getSelectedIndex());
                    //the two method take 5 variables an arguments and return it
                    double ds = (double)cw.CubeWood(Integer.parseInt(ttoll),
                            Integer.parseInt(dtens.getText()),
                            Double.parseDouble(dttol.getText()),
                            Double.parseDouble(daard.getText()),
                            Double.parseDouble(dertfaa.getText()));
                    double ls = (double)s.Plank(Integer.parseInt(lttoll),
                            Integer.parseInt(ltens.getText()),
                            Double.parseDouble(lttol.getText()),
                            Double.parseDouble(laard.getText()),
                            Double.parseDouble(lertfaa.getText()));
                    //this line sumition of two methods in variable dssum
                    double dssum = (ls + ds);
                    //the two lines print the value of on frame in each panels Cm
                    dtotal.setText(ds + " Cm");
                    ltotal.setText(ls + " Cm");
                    
                       //gtotal.setText(dssum + " Cm");
                       
                    //this line put the value in metter price   
                    double cash = Integer.parseInt(mtotal.getText());
                       
                           
                    //the first line multiplay metter price with sumtion of two methods and return to total price
                    //and last two lines multipluy the each one method  with metter price and return to each panels
                           double cashp = (cash * dssum);
                    double pls=(ls*cash);lsTotal.setText(pls+" EGP");
                    double pds=(ds*cash);dsTotal.setText(pds+" EGP");
                    
                //this line call the method of specialplank
                SpecialPlank SP=new SpecialPlank();
                ////this line to save the context in string variables
String LPanel = NPanel.getItemAt(NPanel.getSelectedIndex());
              ////the method take 5 variables an arguments and return it to frame screen
double SsT=(double)SP.SpecialPlank(Integer.parseInt(LPanel),
        Integer.parseInt(Stens.getText()),
        Double.parseDouble(HSize.getText()),
        Double.parseDouble(WSize.getText()),
        Double.parseDouble(LSize.getText()));
Scalc.setText(SsT+" Cm");


//this line the total number of palete user want get it string and put it string
String number=nump.getText();

//the sumtion of three methods to get total
double st=(((SsT)+(ls))+(ds));
//this mthod to math round the double get it in small image
st=Math.round(st*100.0)/100.0;

System.out.print(st);

gtotal.setText(st+" Cm");
//quant save on number of all palete user want it 
int quant=Integer.parseInt(number);
//paletesum save on metter price 
int paletesnum=Integer.parseInt(mtotal.getText());
//cashDs multipluy Sst method with metter price
double cashDS=(SsT*paletesnum);
SpecialTotal.setText(cashDS+" EGP");
//sTCash the sumtion of standard with out Ds and Different size
double sTCash=(cashp+cashDS);
//TCash multipluy sTCash with metter price
long TCash=  ((long)((sTCash)*(quant)));
ptotal.setText(sTCash + "  EGP");
totalp.setText("Total cash of "+ptotals+" paletes = "+TCash+" EGP");} 
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "               Error \n\n"
                        + "Check value is not entered..!!!!");
                }
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.hide();
//new Main(wlname.getText()).setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyTyped
        /*        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            evt.consume();
        }*/
    }//GEN-LAST:event_jButton1KeyTyped

    private void baaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baaActionPerformed
        if (baa.isSelected()) {
            lertfaa.setText(lertfaa.getText() + ".");

        } else if (!baa.isSelected()) {
            lertfaa.setText("");

        }  // TODO add your handling code here:
    }//GEN-LAST:event_baaActionPerformed

    private void cttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cttActionPerformed
        if (ctt.isSelected()) {
            lttol.setText(lttol.getText() + ".");

        } else if (!ctt.isSelected()) {
            lttol.setText("");

        }
    }//GEN-LAST:event_cttActionPerformed

    private void cddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cddActionPerformed
        if (cdd.isSelected()) {
            laard.setText(laard.getText() + ".");

        } else if (!cdd.isSelected()) {
            laard.setText("");
        }
    }//GEN-LAST:event_cddActionPerformed

    private void dddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dddActionPerformed
        if (ddd.isSelected()) {
            dertfaa.setText(dertfaa.getText() + ".");
        } else if (!ddd.isSelected()) {
            dertfaa.setText("");
        }
    }//GEN-LAST:event_dddActionPerformed

    private void bdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdaActionPerformed
        if (bda.isSelected()) {
            daard.setText(daard.getText() + ".");
        } else if (!bda.isSelected()) {
            daard.setText("");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_bdaActionPerformed

    private void cdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdtActionPerformed
        if (cdt.isSelected()) {
            dttol.setText(dttol.getText() + ".");
        } else if (!cdt.isSelected()) {
            dttol.setText("");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cdtActionPerformed

    private void nnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nnewActionPerformed
        dttol.setText("");
        daard.setText("");
        dertfaa.setText("");
        lttol.setText("");
        laard.setText("");
        lertfaa.setText("");
        dtotal.setText("0.00 Cm");
        ltotal.setText("0.00 Cm");
        gtotal.setText("0.00 Cm");
        ptotal.setText("0.00 EGP");
    }//GEN-LAST:event_nnewActionPerformed

    private void lttolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lttolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lttolActionPerformed

    private void dttolKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dttolKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_dttolKeyTyped

    private void daardKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_daardKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_daardKeyTyped

    private void dertfaaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dertfaaKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_dertfaaKeyTyped

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if (dttol.getText().equals("") || daard.getText().equals("") ||
                    dertfaa.getText().equals("") || lttol.getText().equals("") || 
                    laard.getText().equals("") || lertfaa.getText().equals("")) {

                JOptionPane.showMessageDialog(null, "Enter the values!!!");
            } else {
                try {
                    CubeWood cw = new CubeWood();
                    Plank s = new Plank();String ptotals=nump.getText();
                    //float num = Float.parseFloat(dtens.getText());
                    String ttoll = dnum.getItemAt(dnum.getSelectedIndex());
                    String lttoll = lnum.getItemAt(lnum.getSelectedIndex());
                    double ds = cw.CubeWood(Integer.parseInt(ttoll),
                            Integer.parseInt(dtens.getText()),
                            Double.parseDouble(dttol.getText()),
                            Double.parseDouble(daard.getText()),
                            Double.parseDouble(dertfaa.getText()));
                    double ls = s.Plank(Integer.parseInt(lttoll),
                            Integer.parseInt(ltens.getText()),
                            Double.parseDouble(lttol.getText()),
                            Double.parseDouble(laard.getText()),
                            Double.parseDouble(lertfaa.getText()));
                    double dssum = (ls + ds);
                    dtotal.setText(ds + " Cm");
                    ltotal.setText(ls + " Cm");
                    gtotal.setText(dssum + " Cm");
                    double cash = Integer.parseInt(mtotal.getText());
                    double cashp = (cash * dssum);
                    
                
                SpecialPlank SP=new SpecialPlank();
String LPanel = NPanel.getItemAt(NPanel.getSelectedIndex());

double ST=SP.SpecialPlank(
        Integer.parseInt(LPanel),
        Integer.parseInt(Stens.getText()),
        Double.parseDouble(HSize.getText()),
        Double.parseDouble(WSize.getText()),
        Double.parseDouble(LSize.getText()));
Scalc.setText(ST+" Cm");
String number=nump.getText();
int quant=Integer.parseInt(number);
int paletesnum=Integer.parseInt(mtotal.getText());
double cashDS=(ST*paletesnum);
SpecialTotal.setText(cashDS+" EGP");
double sTCash=(cashp+cashDS);
long TCash= (long) ((cashp+cashDS)*(quant));
ptotal.setText(sTCash + "  EGP");
totalp.setText("Total cash of "+ptotals+" paletes = "+TCash+" EGP");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Check values.....");
                }
            }
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void neworderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neworderActionPerformed
neworder.setEnabled(false);//lertfaa.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_neworderActionPerformed

    private void SsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SsActionPerformed
if(Ss.isSelected()){
    Ds.setSelected(false);
    Dsize.setVisible(false);
    LSize.setText("0");WSize.setText("0");HSize.setText("0");

}
        
    }//GEN-LAST:event_SsActionPerformed

    private void DsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DsActionPerformed
if(Ds.isSelected()){
Ds.setSelected(true);
    Ss.setSelected(false);
Dsize.setVisible(true);
LSize.setText("");WSize.setText("");HSize.setText("");
}
    }//GEN-LAST:event_DsActionPerformed

    private void dWSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dWSizeActionPerformed
        if(dWSize.isSelected()){
        WSize.setText(WSize.getText()+".");
        }
    }//GEN-LAST:event_dWSizeActionPerformed

    private void dLSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dLSizeActionPerformed
if(dLSize.isSelected()){
LSize.setText(LSize.getText()+".");
}

    }//GEN-LAST:event_dLSizeActionPerformed

    private void numpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numpKeyTyped
char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_numpKeyTyped

    private void mtotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mtotalKeyTyped
char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();}
    }//GEN-LAST:event_mtotalKeyTyped

    private void StensKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StensKeyTyped
char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();}
    }//GEN-LAST:event_StensKeyTyped

    private void ltensKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ltensKeyTyped
char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();}
    }//GEN-LAST:event_ltensKeyTyped

    private void dtensKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dtensKeyTyped
char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();}
    }//GEN-LAST:event_dtensKeyTyped

    private void WSizeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_WSizeKeyTyped
char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();}
    }//GEN-LAST:event_WSizeKeyTyped

    private void LSizeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LSizeKeyTyped
char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();}
    }//GEN-LAST:event_LSizeKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ppalete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ppalete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ppalete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ppalete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ppalete(" ").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Ds;
    private javax.swing.JPanel Dsize;
    private javax.swing.JTextField HSize;
    private javax.swing.JTextField LSize;
    private javax.swing.JComboBox<String> NPanel;
    private javax.swing.JLabel Scalc;
    private javax.swing.JLabel SpecialTotal;
    private javax.swing.JRadioButton Ss;
    private javax.swing.JTextField Stens;
    private javax.swing.JTextField WSize;
    private javax.swing.JCheckBox baa;
    private javax.swing.JCheckBox bda;
    private javax.swing.JCheckBox cdd;
    private javax.swing.JCheckBox cdt;
    private javax.swing.JCheckBox ctt;
    private javax.swing.JCheckBox dLSize;
    private javax.swing.JCheckBox dWSize;
    private javax.swing.JTextField daard;
    private javax.swing.JCheckBox ddd;
    private javax.swing.JTextField dertfaa;
    private javax.swing.JComboBox<String> dnum;
    private javax.swing.JLabel dsTotal;
    private javax.swing.JTextField dtens;
    private javax.swing.JLabel dtotal;
    private javax.swing.JTextField dttol;
    private javax.swing.JLabel gtotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField laard;
    private javax.swing.JTextField lertfaa;
    private javax.swing.JComboBox<String> lnum;
    private javax.swing.JLabel lsTotal;
    private javax.swing.JTextField ltens;
    private javax.swing.JLabel ltotal;
    private javax.swing.JTextField lttol;
    private javax.swing.JTextField mtotal;
    private javax.swing.JButton neworder;
    private javax.swing.JButton nnew;
    private javax.swing.JTextField nump;
    private javax.swing.JLabel ptotal;
    private javax.swing.JLabel totalp;
    private javax.swing.JLabel wlname;
    // End of variables declaration//GEN-END:variables
}
